### ISSUE TITLE
Are you planning on maintaing this repository as public?

### ISSUE THREAD

**Issue by jjjimenez100** [gigerbytes/ncov-ph-data#1]
Hi there,

Good work on parsing those arciv json responses as well as the DOH's daily reports (kind of curious rn on to where DOH uploads those pdf files? Tried looking into their site, but the only thing I can get are their infographics)

Also, are you planning on maintaining this repository as a public one? I'm currently planning on plotting these data you have on an actual map (using this repo as the data source) and integrating tensorflowjs for outputting some predicted changes of values overtime.

Of course, no commercial interest or whatsoever. Just wanted to try out some react-typescript and tensorflow-js goodness.

**Comment by gigerbytes** [comment]
Hi!

Actually I don't know where the DOH uploads the PDF files, i got the ones i found from this telegram group https://t.me/phcoronavirus , but they haven't uploaded any new ones in a while so I assume the DOH stopped creating/publishing them as they've also stopped putting the `status` field in their json.

I plan to maintain the dataset and go for it! Would love to see what you create.

**Comment by trjoshjimenez** [comment]
Thanks a lot!

**Comment by jjjimenez100** [comment]
Thanks mate!
