### ISSUE TITLE
API service

### ISSUE THREAD

**Issue by sorxrob** [gigerbytes/ncov-ph-data#2]
Hi!

I'm currently serving an [API](https://coronavirus-ph-api.herokuapp.com/) of cases, lockdowns, etc. and want to use this data as my source. 

My current source is from wikipedia but the page structure keeps on updating, so the API keeps on breaking. Your source might be a good one! Can I use it? I'll add your repo to the source list.

Another question, are the coordinates in your csv the locations of the hospitals or the place of residence of patients? Also, looks like DOH stopped updating status field?

Thank you!

**Comment by gigerbytes** [comment]
Hey, sorry for the late reply, didn't see this.

1.  I would be happy if you use it!
2. Coordinates are for hospitals
3. Yes, DOH stopped updating status field on march 19

**Comment by sorxrob** [comment]
> Hey, sorry for the late reply, didn't see this.
> 
> 1. I would be happy if you use it!
> 2. Coordinates are for hospitals
> 3. Yes, DOH stopped updating status field on march 19

Thank you :)
